package com.threading;

public class Demo1 extends Thread implements Runnable{
	
	//implicitly invoked when the thread executes 
	public void run() {
		
		
		String threadName=Thread.currentThread().getName();
		
		for(int i=1;i<=10;i++) {
			System.out.println(i +" :generated by, "+threadName);
			try {
				Thread.sleep(2000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	
	}
	
	
	public static void main(String[] args) {
		System.out.println(Thread.currentThread().getName()+" "+Thread.currentThread().getId());
		
		Demo1 demo1=new Demo1();
		Demo1 demo2=new Demo1();
		Demo1 demo3=new Demo1();
		//demo1.setName("MyThread");
		//demo1.run();
		demo1.start();//thread-0
		demo2.start();//thread-1
		demo3.start();//thread-2
		
		Thread t1=new Thread();
		
		
		
	}
}
